package core

import (
	"crashpanel/database"
	"crashpanel/models"
	"fmt"
	"os"
	"strings"
)

// GenerateConfig 根据当前设置生成核心配置文件
func GenerateConfig() error {
	var s models.Settings
	if err := database.DB.First(&s).Error; err != nil {
		return err
	}
	var dns models.DNSConfig
	database.DB.First(&dns)

	switch s.CoreType {
	case "singbox":
		return generateSingbox(&s, &dns)
	default:
		return generateMeta(&s, &dns)
	}
}

// generateMeta 生成 Clash Meta (mihomo) config.yaml
func generateMeta(s *models.Settings, dns *models.DNSConfig) error {
	if err := os.MkdirAll(s.CoreWorkDir, 0755); err != nil {
		return err
	}

	dnsMode := s.DNSMod
	if dnsMode == "" {
		dnsMode = "redir-host"
	}

	nameservers := splitTrim(dns.Nameserver)
	fallbacks := splitTrim(dns.Fallback)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`# Generated by CrashPanel
mixed-port: %d
redir-port: %d
tproxy-port: %d
external-controller: 0.0.0.0:%d
allow-lan: true
mode: rule
log-level: info

dns:
  enable: true
  listen: 0.0.0.0:%d
  enhanced-mode: %s
  nameserver:
`, s.MixPort, s.RedirPort, s.TproxyPort, s.DashboardPort, s.DNSPort, dnsMode))

	for _, ns := range nameservers {
		sb.WriteString(fmt.Sprintf("    - %s\n", ns))
	}

	if len(fallbacks) > 0 {
		sb.WriteString("  fallback:\n")
		for _, fb := range fallbacks {
			sb.WriteString(fmt.Sprintf("    - %s\n", fb))
		}
		if dns.FallbackFilter != "" {
			sb.WriteString(fmt.Sprintf("  fallback-filter:\n    geoip: true\n    geoip-code: CN\n"))
		}
	}

	if dnsMode == "fake-ip" && dns.FakeIPFilter != "" {
		filters := splitTrim(dns.FakeIPFilter)
		sb.WriteString("  fake-ip-filter:\n")
		for _, f := range filters {
			sb.WriteString(fmt.Sprintf("    - '%s'\n", f))
		}
	}

	sb.WriteString(`
proxies: []
proxy-groups: []
rules:
  - MATCH,DIRECT
`)

	path := s.CoreWorkDir + "/config.yaml"
	return os.WriteFile(path, []byte(sb.String()), 0644)
}

// generateSingbox 生成 sing-box config.json
func generateSingbox(s *models.Settings, dns *models.DNSConfig) error {
	dir := s.CoreWorkDir + "/jsons"
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	nameservers := splitTrim(dns.Nameserver)
	var nsJSON []string
	for _, ns := range nameservers {
		nsJSON = append(nsJSON, fmt.Sprintf(`{"address": "%s"}`, ns))
	}

	cfg := fmt.Sprintf(`{
  "log": {"level": "info"},
  "dns": {
    "servers": [%s],
    "rules": []
  },
  "inbounds": [
    {
      "type": "mixed",
      "listen": "::",
      "listen_port": %d
    },
    {
      "type": "redirect",
      "listen": "::",
      "listen_port": %d
    },
    {
      "type": "tproxy",
      "listen": "::",
      "listen_port": %d
    }
  ],
  "outbounds": [
    {"type": "direct", "tag": "direct"},
    {"type": "block",  "tag": "block"}
  ],
  "route": {
    "rules": [],
    "final": "direct"
  },
  "experimental": {
    "clash_api": {
      "external_controller": "0.0.0.0:%d"
    }
  }
}`, strings.Join(nsJSON, ", "), s.MixPort, s.RedirPort, s.TproxyPort, s.DashboardPort)

	path := dir + "/config.json"
	return os.WriteFile(path, []byte(cfg), 0644)
}

func splitTrim(s string) []string {
	var result []string
	for _, part := range strings.Split(s, ",") {
		p := strings.TrimSpace(part)
		if p != "" {
			result = append(result, p)
		}
	}
	return result
}
