package core

import (
	"crashpanel/database"
	"crashpanel/models"
	"crashpanel/service/subscribe"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

// GenerateConfig 生成核心配置文件
// 逻辑：取当前选中的规则模板 → 解析 proxy-groups/rules 骨架
//       → 遍历所有提供者生成 proxy-providers 块
//       → 拼装成完整 config.yaml
func GenerateConfig() error {
	var s models.Settings
	if err := database.DB.First(&s).Error; err != nil {
		return err
	}
	var dns models.DNSConfig
	database.DB.First(&dns)

	switch s.CoreType {
	case "singbox":
		return generateSingbox(&s, &dns)
	default:
		return generateMeta(&s, &dns)
	}
}

// ── Clash Meta ──────────────────────────────────────────────────────────────

func generateMeta(s *models.Settings, dns *models.DNSConfig) error {
	if err := os.MkdirAll(s.CoreWorkDir, 0755); err != nil {
		return err
	}

	// 1. 读取所有 provider
	var subs []models.Subscription
	database.DB.Find(&subs)

	// 2. 构建 DNS 头部
	header := buildMetaHeader(s, dns)

	// 3. 根据是否有 provider 决定配置策略
	var body string
	if len(subs) == 0 {
		body = "\nproxies: []\nproxy-groups: []\nrules:\n  - MATCH,DIRECT\n"
	} else {
		// 4. 获取规则模板
		tmpl, err := fetchTemplate(s.CoreWorkDir)
		if err != nil {
			// 模板获取失败，降级为简单配置
			body = buildSimpleBody(subs)
		} else {
			// 5. 用模板拼装完整配置
			body, err = buildBodyFromTemplate(tmpl, subs, s)
			if err != nil {
				body = buildSimpleBody(subs)
			}
		}
	}

	path := s.CoreWorkDir + "/config.yaml"
	return os.WriteFile(path, []byte(header+body), 0644)
}

// buildMetaHeader 生成 yaml 头部（端口、DNS 等）
func buildMetaHeader(s *models.Settings, dns *models.DNSConfig) string {
	dnsMode := s.DNSMod
	if dnsMode == "" {
		dnsMode = "redir-host"
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`# Generated by CrashPanel
mixed-port: %d
redir-port: %d
tproxy-port: %d
external-controller: 0.0.0.0:%d
allow-lan: true
mode: rule
log-level: info

dns:
  enable: true
  listen: 0.0.0.0:%d
  enhanced-mode: %s
  nameserver:
`, s.MixPort, s.RedirPort, s.TproxyPort, s.DashboardPort, s.DNSPort, dnsMode))

	for _, ns := range splitTrim(dns.Nameserver) {
		sb.WriteString(fmt.Sprintf("    - %s\n", ns))
	}
	if fallbacks := splitTrim(dns.Fallback); len(fallbacks) > 0 {
		sb.WriteString("  fallback:\n")
		for _, fb := range fallbacks {
			sb.WriteString(fmt.Sprintf("    - %s\n", fb))
		}
		if dns.FallbackFilter != "" {
			sb.WriteString("  fallback-filter:\n    geoip: true\n    geoip-code: CN\n")
		}
	}
	if dnsMode == "fake-ip" {
		filters := splitTrim(dns.FakeIPFilter)
		if len(filters) > 0 {
			sb.WriteString("  fake-ip-filter:\n")
			for _, f := range filters {
				sb.WriteString(fmt.Sprintf("    - '%s'\n", f))
			}
		}
	}
	return sb.String()
}

// fetchTemplate 获取当前选中的规则模板内容
func fetchTemplate(workDir string) (string, error) {
	var tmpl models.RuleTemplate
	// 优先取 is_default=true 的模板
	if err := database.DB.Where("is_default = ?", true).First(&tmpl).Error; err != nil {
		// 没有默认模板，取第一个
		if err2 := database.DB.First(&tmpl).Error; err2 != nil {
			return "", fmt.Errorf("no template found")
		}
	}

	// 如果是本地路径且文件存在，直接读取
	if tmpl.LocalPath != "" {
		if data, err := os.ReadFile(tmpl.LocalPath); err == nil {
			return string(data), nil
		}
	}

	// 从远程下载
	if tmpl.URL == "" {
		return "", fmt.Errorf("template has no url")
	}

	cacheDir := workDir + "/templates"
	if err := os.MkdirAll(cacheDir, 0755); err != nil {
		return "", err
	}
	cachePath := fmt.Sprintf("%s/template_%d.ini", cacheDir, tmpl.ID)

	// 检查缓存（1天内不重新下载）
	if info, err := os.Stat(cachePath); err == nil {
		if time.Since(info.ModTime()) < 24*time.Hour {
			if data, err := os.ReadFile(cachePath); err == nil {
				return string(data), nil
			}
		}
	}

	// 下载
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Get(tmpl.URL)
	if err != nil {
		return "", fmt.Errorf("download template failed: %v", err)
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", err
	}

	// 缓存到本地
	_ = os.WriteFile(cachePath, data, 0644)

	// 同时更新 LocalPath
	database.DB.Model(&tmpl).Update("local_path", cachePath)

	return string(data), nil
}

// buildBodyFromTemplate 用 ini 模板 + providers 生成 yaml body
// ini 格式解析：
//   ruleset=组名,规则URL  → rules
//   custom_proxy_group=名`类型`...  → proxy-groups
func buildBodyFromTemplate(ini string, subs []models.Subscription, s *models.Settings) (string, error) {
	// 解析 proxy-groups
	groups := parseProxyGroups(ini, subs)
	// 解析 rules
	rules := parseRules(ini)

	var sb strings.Builder

	// proxy-providers
	sb.WriteString("\nproxy-providers:\n")
	hasURI := false
	for _, sub := range subs {
		if sub.LinkType == models.LinkTypeURI {
			hasURI = true
			continue
		}
		filePath := subscribe.ProviderFilePath(&sub)
		healthInterval := sub.HealthInterval
		if healthInterval == 0 {
			healthInterval = 3
		}
		updateInterval := sub.UpdateInterval
		if updateInterval == 0 {
			updateInterval = 12
		}
		ua := sub.UserAgent
		if ua == "" {
			ua = "clash.meta"
		}

		if sub.LinkType == models.LinkTypeFile {
			// 本地文件类型
			sb.WriteString(fmt.Sprintf(`  %s:
    type: file
    path: %s
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: %d
`, providerTag(sub), filePath, healthInterval*60))
		} else {
			// URL 类型
			sb.WriteString(fmt.Sprintf(`  %s:
    type: http
    url: "%s"
    path: %s
    interval: %d
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: %d
    header:
      User-Agent: ["%s"]
    override:
      udp: true
      skip-cert-verify: true
    filter: "%s"
    exclude-filter: "%s"
`, providerTag(sub), sub.URL, filePath,
				updateInterval*3600, healthInterval*60,
				ua, sub.Include, sub.Exclude))
		}
	}

	// URI group 作为一个整体 provider
	if hasURI {
		uriPath := "/etc/crashpanel/core/providers/uri_group"
		sb.WriteString(fmt.Sprintf(`  Uri_group:
    type: file
    path: %s
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: 180
`, uriPath))
	}

	// 收集所有 provider tags（用于填入 proxy-groups 的 use 字段）
	var allTags []string
	for _, sub := range subs {
		if sub.LinkType != models.LinkTypeURI {
			allTags = append(allTags, providerTag(sub))
		}
	}
	if hasURI {
		allTags = append(allTags, "Uri_group")
	}
	allTagsStr := strings.Join(allTags, ", ")

	// proxy-groups（将 {providers_tags} 替换为实际 tag 列表）
	sb.WriteString("\nproxy-groups:\n")
	for _, g := range groups {
		g = strings.ReplaceAll(g, "{providers_tags}", allTagsStr)
		sb.WriteString(g)
	}

	// rules
	sb.WriteString("\nrules:\n")
	for _, r := range rules {
		sb.WriteString(fmt.Sprintf("  - %s\n", r))
	}

	return sb.String(), nil
}

// parseProxyGroups 解析 ini 中 custom_proxy_group 行，转为 clash yaml 格式
// 格式：名称`类型`成员1`成员2`...`[url`interval`tolerance]
func parseProxyGroups(ini string, subs []models.Subscription) []string {
	var groups []string
	// 收集所有 provider tags
	var allTags []string
	for _, sub := range subs {
		allTags = append(allTags, providerTag(sub))
	}

	for _, line := range strings.Split(ini, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "custom_proxy_group=") {
			continue
		}
		line = strings.TrimPrefix(line, "custom_proxy_group=")
		parts := strings.Split(line, "`")
		if len(parts) < 2 {
			continue
		}

		name := parts[0]
		gtype := parts[1]
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("  - name: \"%s\"\n    type: %s\n", name, gtype))

		// url-test / fallback 需要 url 和 interval
		testURL := "https://www.gstatic.com/generate_204"
		interval := 300
		tolerance := 50

		// 解析成员
		var proxies []string
		var useProviders []string

		for _, p := range parts[2:] {
			p = strings.TrimSpace(p)
			if p == "" {
				continue
			}
			// url-test 参数行（http://...）
			if strings.HasPrefix(p, "http") {
				testURL = p
				continue
			}
			// 纯数字 = interval 或 tolerance
			if isNum(p) {
				if interval == 300 {
					interval, _ = parseInt(p)
				} else {
					tolerance, _ = parseInt(p)
				}
				continue
			}
			// 通配符 .* = 使用所有 providers
			if p == ".*" {
				useProviders = append(useProviders, allTags...)
				continue
			}
			// 正则过滤（含特殊字符，作为 filter）
			if isRegex(p) {
				// 用 filter 字段过滤 providers
				for _, tag := range allTags {
					useProviders = append(useProviders, tag)
				}
				sb.WriteString(fmt.Sprintf("    filter: \"%s\"\n", p))
				continue
			}
			// [] 前缀的 proxy 引用
			if strings.HasPrefix(p, "[]") {
				proxies = append(proxies, strings.TrimPrefix(p, "[]"))
			} else {
				proxies = append(proxies, p)
			}
		}

		// 写入 use（providers）
		if len(useProviders) > 0 {
			// 去重
			seen := map[string]bool{}
			sb.WriteString("    use:\n")
			for _, t := range useProviders {
				if !seen[t] {
					seen[t] = true
					sb.WriteString(fmt.Sprintf("      - %s\n", t))
				}
			}
		}

		// 写入 proxies
		if len(proxies) > 0 {
			sb.WriteString("    proxies:\n")
			for _, px := range proxies {
				sb.WriteString(fmt.Sprintf("      - %s\n", px))
			}
		}

		// url-test / fallback 额外参数
		if gtype == "url-test" || gtype == "fallback" {
			sb.WriteString(fmt.Sprintf("    url: \"%s\"\n    interval: %d\n    tolerance: %d\n",
				testURL, interval, tolerance))
		}

		groups = append(groups, sb.String())
	}

	// 如果模板没解析出 group，生成默认的
	if len(groups) == 0 {
		groups = buildDefaultGroups(allTags)
	}
	return groups
}

// parseRules 解析 ini 中 ruleset 行，转为 clash rules 格式
// ruleset=组名,规则URL 或 ruleset=组名,[]FINAL
func parseRules(ini string) []string {
	var rules []string
	for _, line := range strings.Split(ini, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "ruleset=") {
			continue
		}
		line = strings.TrimPrefix(line, "ruleset=")
		idx := strings.Index(line, ",")
		if idx < 0 {
			continue
		}
		group := line[:idx]
		target := line[idx+1:]

		if strings.HasPrefix(target, "[]") {
			// 内建规则，如 []FINAL → MATCH
			builtin := strings.TrimPrefix(target, "[]")
			if builtin == "FINAL" {
				rules = append(rules, fmt.Sprintf("MATCH,%s", group))
			} else {
				rules = append(rules, fmt.Sprintf("MATCH,%s", group))
			}
		} else {
			// 远程规则集，作为 RULE-SET 引用（mihomo 支持）
			rules = append(rules, fmt.Sprintf("RULE-SET,%s,%s", rulesetTag(target), group))
		}
	}

	if len(rules) == 0 {
		rules = []string{"GEOIP,CN,DIRECT", "MATCH,🚀 节点选择"}
	}
	return rules
}

// buildSimpleBody 降级方案：无模板时的简单配置
func buildSimpleBody(subs []models.Subscription) string {
	var sb strings.Builder
	sb.WriteString("\nproxy-providers:\n")
	for _, sub := range subs {
		filePath := subscribe.ProviderFilePath(&sub)
		sb.WriteString(fmt.Sprintf(`  %s:
    type: file
    path: %s
    health-check:
      enable: true
      interval: 600
      url: "https://www.gstatic.com/generate_204"
`, providerTag(sub), filePath))
	}

	var allTags []string
	for _, sub := range subs {
		allTags = append(allTags, providerTag(sub))
	}

	sb.WriteString("\nproxy-groups:\n")
	for _, g := range buildDefaultGroups(allTags) {
		sb.WriteString(g)
	}
	sb.WriteString("\nrules:\n  - GEOIP,CN,DIRECT\n  - MATCH,🚀 节点选择\n")
	return sb.String()
}

func buildDefaultGroups(allTags []string) []string {
	useBlock := ""
	for _, t := range allTags {
		useBlock += fmt.Sprintf("      - %s\n", t)
	}
	return []string{
		fmt.Sprintf("  - name: \"🚀 节点选择\"\n    type: select\n    use:\n%s    proxies:\n      - DIRECT\n", useBlock),
		fmt.Sprintf("  - name: \"♻️ 自动选择\"\n    type: url-test\n    use:\n%s    url: \"https://www.gstatic.com/generate_204\"\n    interval: 300\n    tolerance: 50\n", useBlock),
	}
}

func providerTag(sub models.Subscription) string {
	// 用名称去掉特殊字符作为 tag
	tag := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			return r
		}
		return '_'
	}, sub.Name)
	if tag == "" {
		tag = fmt.Sprintf("sub_%d", sub.ID)
	}
	return tag
}

func rulesetTag(ruleURL string) string {
	// 取 URL 最后一段作为 ruleset tag
	parts := strings.Split(ruleURL, "/")
	name := parts[len(parts)-1]
	name = strings.TrimSuffix(name, ".list")
	name = strings.TrimSuffix(name, ".yaml")
	return name
}

func isNum(s string) bool {
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return len(s) > 0
}

func parseInt(s string) (int, error) {
	n := 0
	for _, c := range s {
		n = n*10 + int(c-'0')
	}
	return n, nil
}

func isRegex(s string) bool {
	for _, c := range s {
		if c == '|' || c == '(' || c == ')' || c == '[' || c == '\\' || c == '^' || c == '$' {
			return true
		}
	}
	return false
}

// ── sing-box ─────────────────────────────────────────────────────────────────

func generateSingbox(s *models.Settings, dns *models.DNSConfig) error {
	dir := s.CoreWorkDir + "/jsons"
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	nameservers := splitTrim(dns.Nameserver)
	var nsJSON []string
	for _, ns := range nameservers {
		nsJSON = append(nsJSON, fmt.Sprintf(`{"address": "%s"}`, ns))
	}
	cfg := fmt.Sprintf(`{
  "log": {"level": "info"},
  "dns": {"servers": [%s], "rules": []},
  "inbounds": [
    {"type": "mixed",    "listen": "::", "listen_port": %d},
    {"type": "redirect", "listen": "::", "listen_port": %d},
    {"type": "tproxy",   "listen": "::", "listen_port": %d}
  ],
  "outbounds": [
    {"type": "direct", "tag": "direct"},
    {"type": "block",  "tag": "block"}
  ],
  "route": {"rules": [], "final": "direct"},
  "experimental": {"clash_api": {"external_controller": "0.0.0.0:%d"}}
}`, strings.Join(nsJSON, ", "), s.MixPort, s.RedirPort, s.TproxyPort, s.DashboardPort)

	return os.WriteFile(dir+"/config.json", []byte(cfg), 0644)
}

func splitTrim(s string) []string {
	var result []string
	for _, part := range strings.Split(s, ",") {
		if p := strings.TrimSpace(part); p != "" {
			result = append(result, p)
		}
	}
	return result
}
